version: '3'

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        bundle_on_build: "false"
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DATABASE_USERNAME=postgres
    volumes:
      - ./app:/app
      - ./bundle:/bundle

  db:
    image: postgres:10.3
    ports:
      - '5432:5432'
